= Déroulement d'une partie
:doctype: book

Une partie se déroule en trois étapes:

* Le cadrage
* Les préparatifs
* L'immersion
* Le débrief

== Le cadrage

Le cadrage a définir l'univers de jeu et à mettre en phase tous les joueurs sur la partie à jouer.

On pourra s'appuyer sur les questions suivantes du cadrage.

Suivant le mode de jeu, cela peut être la Destinée qui répond à toutes les questions et présente ainsi le monde mais on peut aussi passer 2 minutes par question pour mettre en commun les réponses validés par tous.

Dans cette phase, il s'agit juste de choisir l'univers de jeu et d'en avoir une vision commune au niveau des grandes lignes. On ne détaille pas dans cette étape.

Durée: variable mais ne devrait pas être trop long (30 minutes)

[.underline]#Ressources#:

* *questions -> cadrage*: des questions pour le cadrage


== Les préparatifs

Dans cette étape, il faut préparer les protagonistes, le monde et l'intrigue qui sera jouée.

Durée: 30 minutes

=== Préparation du monde

En mode tresse, c'est Cosmos qui s'en charge.

Cosmos peut utiliser des feuilles A4 pliées en 2 sous forme de petits livrets pour développer ses lexiques.

Dans cette phase:

- on crée des lexiques de noms
- on étoffe les éléments du cadrage (sous forme de lexiques)
- on présente aux autres ce que tout le monde doit connaître sur le monde

Note: on peut échanger des petits papiers avec Chaos pour cacher des infos aux Héros.

=== Préparation des héros

En mode tresse, chaque Héros crée son héros.

Il suffit de prendre une feuille A4 et de répondre aux questions suivantes.

Les réponses pourront servir de traits par la suite dans les oppositions.

[.underline]#Ressources#:

* *questions -> héros* : un questionnaire simple pour créer un héros
* *questions -> groupe* : un questionnaire simple pour créer un groupe de héros

=== Préparation de l'histoire

En mode tresse, c'est Chaos qui s'en charge.

Chaos peut utiliser des feuilles A4 pliée en 2 mais utilisée horizontalement une fois pliée pour pouvoir cacher l'info aux autres.

- on pioche 2 intrigues et on en choisit 1 ou on mixe les 2.
- on réfléchit à des enjeux éventuels (en gros des questions auxquels il faudra répondre pendant le jeu)
- on développe au moins 1 menace qui se développe en au moins 3 étapes (idéalement 6).

[.underline]#Ressources#:

* *lexiques -> intrigues* : une liste de 34 intrigues avec tirage au sort à base de cartes à jouer.
* *questions -> menace* : des questions à se poser quand on veut créer une menace

== L'immersion

=== Début de l'histoire

On commence l'histoire comme on le souhaite mais l'idée est de présenter les protagonistes et de les accrocher c'est à dire de les lier à une intrigue.

[.underline]#Ressources#:

* *questions -> au commencement*: des questions pour commencer le récit.

=== Pendant la partie

On s'appuie essentiellement sur les fiches de héros, groupe, menaces et autres lexiques créés pendant la préparation mais on peut aussi utiliser d'autres lexiques prêts à jouer.

[.underline]#Ressources#:

* *lexiques -> génériques*: un certain nombre de lexiques génériques valables dans n'importe quel univers.


== Le débrief

C'est l'occasion de parler de ce qui a marché ou pas, 
ce qu'on a aimé, ce qu'on aimerait, etc... 

Une façon ludique et immersive est de jouer le débrief en RP, dans une scène où les protagonistes discutent entre eux de ce qu'ils ont vécu,
ou encore en faisant jouer une scène où les protagonistes doivent faire leur rapport à un autre personnage.

[.underline]#Ressources#:

* *questions -> débrief*: des questions à se poser pendant un débrief