= HaDes (HAsard & DEStin)
aleascript@gmail.com
Version 0.1
:doctype: book
//:sectnums:
:toc:
:toclevels: 4
:toc-title: Table des matières
:description: HaDes est un jeu de rôle générique
:keywords: JdR, Solo
:imagesdir: ./img

[quote]
____
L'imagination est une ressource infinie, gratuite et partageable.
____

HaDes est un jeu de rôle comprenant:

* un système générique de résolution sans stats qui se veut *simple*, *réaliste* et *inspirant*
* plusieurs modes de jeu: *solo*, *legacy* (classique), *tresse*
* un système d'oracle (conçu plutôt pour le mode solo)

include::systeme.adoc[]

= Les Modes de jeu 

== Mode tresse

Dans ce mode, on a:

* **Cosmos**: le joueur en charge du monde et du destin
* **Chaos**: le joueur en charge des menaces et de l'intrigue
* **Héros**: les joueurs en charge des protagonistes

Le mode tresse c'est une sorte de jeu de rôles à 2 MJ mais qui ont tous les deux des rôles distincts.

Le mode tresse veut aussi faciliter les parties sur le pouce pour décharger le meneur.

Note: personnalités des joueurs et rôles dans le mode tresse.

- Héros = moi je, immersion
- Chaos = le troll, aime jouer les méchants
- Cosmos = le cinéphile, le littéraire, l'arbitre

En mode tresse, c'est Cosmos qui gère le destin. Et dans les oppositions, il intervient pour ajouter des dés aux protagonistes ou à l'obstacle suivant les dés du destin qu'il a en main. Il doit bien sûr justifier les dés posés par des éléments du contexte.

C'est également Cosmos qui interprète le résultat de l'opposition sauf si Chaos prend la main au nom de l'histoire.

Cela ne gêne normalement pas la fiction car juste après l'interprétation, Chaos peut tout à fait retourner dans la fiction et raconter un élément propre à l'intrigue.

_Règle optionnelle: quand Chaos se saisit de l'interprétation d'un résultat au nom de l'histoire, le destin gagne un point et donc Cosmos gagne un dé protagoniste (bleu). A appliquer si Chaos a tendance à empiéter sur les interprétations de Cosmos._

== Mode legacy

Dans ce mode, on a:

* La **Destinée**: le joueur en charge du monde, des menaces et de l'intrigue (il cumule Cosmos et Chaos du mode tresse en fait).
* Les **Héros**: les joueurs en charge des protagonistes

Lors du cadrage, la **Destinée** répondra aux questions du cadrage mais pourra proposer des choix aux **Héros**.

Note: généralement la Destinée a déjà un univers prêt à jouer dans ce type de mode.

== Mode solo

Un seul joueur joue le rôle de Chaos, Cosmos et des Héros. Il s'appuie dans ce cas sur les Oracles pour rajouter de la surprise et sur le destin pour connaitre l'orientation des événements: positifs ou négatifs ou neutres.

Une autre façon de jouer est de faire en solo des cadrages et des préparations pour préparer une prochaine partie en mode legacy.


= Déroulement d'une partie

Une partie se déroule en trois étapes:

* Le cadrage
* Les préparatifs
* L'immersion

== Le cadrage

Le cadrage a définir l'univers de jeu et de le présenter en répondant aux 6 questions suivantes:

1. OU, QUAND: Quels sont les **lieux types** ? A quelle époque joue-t'on ?
- En particulier: où se déroulera l’action en début de partie?
2. QUI: Quelles sont les **rencontres types** ?
- En particulier: quelle est la population locale, les voisins connus?
3. COMMENT: Quelles sont les **scènes types** du jeu dans cet univers ?
- En particulier: ce que vous aimez ou n'aimez pas dans ce type d'univers
4. QUOI: Quelles sont les **menaces types** ? Quels sont les problèmes ou dangers usuels de cet univers ? Quelles sont les sources connues de conflit ?
5. COMBIEN: Quelles sont les **ressources types** ? Qu'est ce qui a de la valeur dans cet univers ?
- En particulier c'est le moment pour définir les grandes lignes de pouvoir, le groupe des héros, l'économie, la technologie, le système de magie, etc...
6. POURQUOI: Quels sont les **enjeux types**. Quels sont les buts personnels ou collectifs habituels dans cet univers ?
- En particulier: quelles sont les motivations profondes des gens et plus particulièrement des héros (missions types) ?

Suivant le mode de jeu, cela peut être la Destinée qui répond à toutes les questions et présente ainsi le monde mais si on est en mode tresse, on peut passer 2 minutes par question pour mettre en commun les réponses validés par tous.

Dans cette phase, il s'agit juste de choisir l'univers de jeu et d'en avoir une vision commune au niveau des grandes lignes. On ne détaille pas dans cette étape.

Durée: 30 minutes

== Les préparatifs

Dans cette étape, il faut préparer les protagonistes, le monde et l'intrigue qui sera jouée.

Durée: 30 minutes

=== Préparation du monde

En mode tresse, c'est Cosmos qui s'en charge.

Cosmos peut utiliser des feuilles A4 pliées en 2 sous forme de petits livrets pour développer ses lexiques.

Dans cette phase:

- on crée des lexiques de noms
- on étoffe les éléments du cadrage (sous forme de lexiques)
- on présente aux autres ce que tout le monde doit connaître sur le monde

Note: on peut échanger des petits papiers avec Chaos pour cacher des infos aux Héros.

=== Préparation des héros

En mode tresse, chaque Héros crée son héros.

Il suffit de prendre une feuille A4 et de répondre aux questions suivantes.

Les réponses pourront servir de traits par la suite dans les oppositions.

- quel(s) nom(s) me donne-t'on ?
- que voit on quand on me rencontre ?
- quelles sont mes croyances personnelles ?
- quelle est mon occupation ?
- quels sont mes liens d'appartenance ? (En particulier à plusieurs héros la question du groupe sera à déterminer)
- quels sont mes instincts ?
- qu'est ce qui est sacré pour moi ?
- qu'est ce que je déteste ?
- quelles sont mes valeurs ?
- quels sont mes talents et mes atouts ?
- quels sont mes faiblesses et mes failles ?
- ai-je des expressions types ?

=== Préparation de l'histoire

En mode tresse, c'est Chaos qui s'en charge.

Chaos peut utiliser des feuilles A4 pliée en 2 mais utilisée horizontalement une fois pliée pour pouvoir cacher l'info aux autres.

- on pioche 2 intrigues et on en choisit 1 ou on mixe les 2.
- on réfléchit à des enjeux éventuels (en gros des questions auxquels il faudra répondre pendant le jeu)
- on développe au moins 1 menace qui se développe en au moins 3 étapes (idéalement 6).

== L'immersion

=== Début de l'histoire

* Cosmos choisit un lieu.
* Heros déclare pourquoi il est dans ce lieu.
* Chaos amène l'imprevu, quelque chose d'inhabituel qui permettra de faire le lien
entre les héros et une menace ou une intrigue.

include::principes.adoc[]


= Outils 

== Les lexiques

Le Cosmos peut s’appuyer sur des lexiques pour préparer le monde et
ses descriptions. Tout particulièrement pendant la session zéro mais
aussi au fil du jeu, il est utile de noter des listes rapidement
utilisables.

Exemples:

* Des listes de noms
* Des listes décrivant telle ou telle ambiance, lieu
* Des listes de vêtements, d’attitudes, etc...

== Lexiques génériques: qu'est ce qui rend quelque chose intéressant ? 

Ce qui permet de marquer les autres joueurs c'est de créer des éléments narratifs intéressants. Posez-vous donc la question suivant: qu'est ce qui rend intéressant: un objet, un personnage, un lieu, une scène, une menace, une intrigue, etc... ?

Rappel: show, not tell. C'est à dire que le focus est développé en live.

Voici quelques lexiques applicables à n'importe quel contexte.

Ces lexiques sont à disposition de Chaos mais Cosmos peut également se servir des lexiques pour les objets, lieux et personnages.

=== Objet

`#unique`   `#convoité`    `#illégal`

`#n'est pas ce qu'il paraît ou ce qu'on croit`

`#incompréhensible` `#inviolable` `#maudit`

`#la clé de quelque chose` `#possédé`

`#défaillant` `#mouchard` `#empoisonné` `#vital`

`#extrêment fragile` `#indestructible`

* unique
* convoité
* illégal
* n'est pas ce qu'il paraît ou ce qu'on croit
* incompréhensible
* inviolable
* maudit
* la clé de quelque chose
* possédé
* défaillant
* mouchard
* empoisonné
* vital
* extrêmement fragile ou indestructible
* ...

=== Rencontre

* a une particularité physique remarquable
* fourbe (traîtrise, vol, assassinat)
* veut utiliser les héros uniquement pour son propre bénéfice
(intéressé)
* développe des sentiments pour le héros
* veut à tout prix convaincre, convertir, rallier
* si tu n'es pas avec moi, tu es contre moi
* ennemis héréditaires
* veut à tout prix quelque chose qu'a le héros
* moqueur
* ne parle pas la même langue
* la personne recherchée par "tous"
* une célébrité
* sait des choses
* n'est pas ce qu'il prétend ou ce qu'il parait
* pense différemment
* souhaite la mort d'un autre
* suicidaire
* terriblement attirant, repoussant
* dans un état second
* fou, psychopathe
* a des tics nerveux
* prisonnier, cherche à s’évader, s'enfuir
* rejeté par les siens
* la personne est morte ou a disparu quand les héros arrivent

=== Lieu

* malfamé
* interdit
* labyrinthique
* hanté
* illusion
* rempli d'innocents
* sans issue apparente
* sur le point de s’écrouler, d'exploser
* aucun repère apparent
* protégé
* piégé
* ...

=== Scène

* action
* une bagarre explose
* énigme à résoudre
* investigation
* interrogatoire
* marchandage
* diplomatie
* émotions (révélations, confidences, sentiments...)
* poursuite
* concours
* émerveillement
* ...

=== Menace

* la menace en cache une plus grande
* avancer d'un cran
* révéler une catastrophe imminente
* contrecarrer la menace
* discrédite les héros
* observe, espionne les héros
* s'en prend aux proches des héros
* attaque les héros
* renforce ses défenses
* cherche, trouve un nouvel allié
* apparition d'une nouvelle menace
* ...

=== Intrigue

* nouvelle intrigue (story b)
* coup de théâtre, rebondissement
* piste : nouvelle, brouillage ou disparition
* implication personnelle
* ...

== Les menaces

Les menaces (ou agendas, fronts) sont des outils promus par les jeux
propulsés par l’Apocalypse.

Au lieu d’écrire une trame toute faite, on décrit une menace sous
forme de processus dont les étapes se manifestent quand les Héros
échouent ou sont inactifs.

En général, on a 6 étapes qui vont crescendo. La dernière étape étant
alors la manifestation de la catastrophe imminente.

Une menace est également composée de lieux, factions, personnages
(sbires, etc...) , dangers divers associés à elle.

La menace est à rattacher à l’intrigue en cours de manière directe
pour une one shot ou de manière directe ou indirecte pour une
campagne. Pour cela penser à l’enjeu de l’intrigue et cela devrait
vous permettre d’élaborer une menace associée.

Exemple: enquête -> enjeux pour trouver le coupable:

- prouver son innocence: 1. auditionné 2. soupconné 3. suspect 4.
arrêté 5. jugement 6. châtiment
- le recruteur veut accuser untel mais untel est innocent: 1. fausses
infos 2. surveillés 3. empêchés 4. attaqués 5. calomniés 6. éliminés
(d’ici là les Héros se seront sans doute retournés contre le
recruteur).
- le tueur va recommencer: 1. Enquete normale 2. faux coupable arrêté 3. autre meurtre 4. autre meurtre proche des héros 5. le coupable s’en
prend aux héros directement 6. le coupable s’en sort

Ces étapes vous permettront de faire avancer l’intrigue et de monter
la pression d’un cran pour les Héros. A user et abuser surtout en cas
d’échec sur les jets ou si les héros ne font rien pour s’impliquer dans l’intrigue.



include::oracles.adoc[]

include::intrigues.adoc[]

