= Outils
:doctype: book

== Les lexiques

Le Cosmos peut s’appuyer sur des lexiques pour préparer le monde et
ses descriptions. Tout particulièrement pendant la session zéro mais
aussi au fil du jeu, il est utile de noter des listes rapidement
utilisables.

Exemples:

* Des listes de noms
* Des listes décrivant telle ou telle ambiance, lieu
* Des listes de vêtements, d’attitudes, etc...

== Lexiques génériques: qu'est ce qui rend quelque chose intéressant ?

Ce qui permet de marquer les autres joueurs c'est de créer des éléments narratifs intéressants. Posez-vous donc la question suivant: qu'est ce qui rend intéressant: un objet, un personnage, un lieu, une scène, une menace, une intrigue, etc... ?

Rappel: show, not tell. C'est à dire que le focus est développé en live.

Voici quelques lexiques applicables à n'importe quel contexte.

Ces lexiques sont à disposition de Chaos mais Cosmos peut également se servir des lexiques pour les objets, lieux et personnages.

=== Objet

`#unique`   `#convoité`    `#illégal`

`#n'est pas ce qu'il paraît ou ce qu'on croit`

`#incompréhensible` `#inviolable` `#maudit`

`#la clé de quelque chose` `#possédé`

`#défaillant` `#mouchard` `#empoisonné` `#vital`

`#extrêment fragile` `#indestructible`

* unique
* convoité
* illégal
* n'est pas ce qu'il paraît ou ce qu'on croit
* incompréhensible
* inviolable
* maudit
* la clé de quelque chose
* possédé
* défaillant
* mouchard
* empoisonné
* vital
* extrêmement fragile ou indestructible
* ...

=== Rencontre

* a une particularité physique remarquable
* fourbe (traîtrise, vol, assassinat)
* veut utiliser les héros uniquement pour son propre bénéfice
(intéressé)
* développe des sentiments pour le héros
* veut à tout prix convaincre, convertir, rallier
* si tu n'es pas avec moi, tu es contre moi
* ennemis héréditaires
* veut à tout prix quelque chose qu'a le héros
* moqueur
* ne parle pas la même langue
* la personne recherchée par "tous"
* une célébrité
* sait des choses
* n'est pas ce qu'il prétend ou ce qu'il parait
* pense différemment
* souhaite la mort d'un autre
* suicidaire
* terriblement attirant, repoussant
* dans un état second
* fou, psychopathe
* a des tics nerveux
* prisonnier, cherche à s’évader, s'enfuir
* rejeté par les siens
* la personne est morte ou a disparu quand les héros arrivent

=== Lieu

* malfamé
* interdit
* labyrinthique
* hanté
* illusion
* rempli d'innocents
* sans issue apparente
* sur le point de s’écrouler, d'exploser
* aucun repère apparent
* protégé
* piégé
* ...

=== Scène

* action
* une bagarre explose
* énigme à résoudre
* investigation
* interrogatoire
* marchandage
* diplomatie
* émotions (révélations, confidences, sentiments...)
* poursuite
* concours
* émerveillement
* ...

=== Menace

* la menace en cache une plus grande
* avancer d'un cran
* révéler une catastrophe imminente
* contrecarrer la menace
* discrédite les héros
* observe, espionne les héros
* s'en prend aux proches des héros
* attaque les héros
* renforce ses défenses
* cherche, trouve un nouvel allié
* apparition d'une nouvelle menace
* ...

=== Intrigue

* nouvelle intrigue (story b)
* coup de théâtre, rebondissement
* piste : nouvelle, brouillage ou disparition
* implication personnelle
* ...

== Les menaces

Les menaces (ou agendas, fronts) sont des outils promus par les jeux
propulsés par l’Apocalypse.

Au lieu d’écrire une trame toute faite, on décrit une menace sous
forme de processus dont les étapes se manifestent quand les Héros
échouent ou sont inactifs.

En général, on a 6 étapes qui vont crescendo. La dernière étape étant
alors la manifestation de la catastrophe imminente.

Une menace est également composée de lieux, factions, personnages
(sbires, etc...) , dangers divers associés à elle.

La menace est à rattacher à l’intrigue en cours de manière directe
pour une one shot ou de manière directe ou indirecte pour une
campagne. Pour cela penser à l’enjeu de l’intrigue et cela devrait
vous permettre d’élaborer une menace associée.

Exemple: enquête -> enjeux pour trouver le coupable:

- prouver son innocence: 1. auditionné 2. soupconné 3. suspect 4.
arrêté 5. jugement 6. châtiment
- le recruteur veut accuser untel mais untel est innocent: 1. fausses
infos 2. surveillés 3. empêchés 4. attaqués 5. calomniés 6. éliminés
(d’ici là les Héros se seront sans doute retournés contre le
recruteur).
- le tueur va recommencer: 1. Enquete normale 2. faux coupable arrêté 3. autre meurtre 4. autre meurtre proche des héros 5. le coupable s’en
prend aux héros directement 6. le coupable s’en sort

Ces étapes vous permettront de faire avancer l’intrigue et de monter
la pression d’un cran pour les Héros. A user et abuser surtout en cas
d’échec sur les jets ou si les héros ne font rien pour s’impliquer dans l’intrigue.