= Les Modes de jeu
:doctype: book

== Mode tresse

Dans ce mode, on a:

* **Cosmos**: le joueur en charge du monde et du destin
* **Chaos**: le joueur en charge des menaces et de l'intrigue
* **Héros**: les joueurs en charge des protagonistes

Le mode tresse c'est une sorte de jeu de rôles à 2 MJ mais qui ont tous les deux des rôles distincts.

Le mode tresse veut aussi faciliter les parties sur le pouce pour décharger le meneur.

Note: personnalités des joueurs et rôles dans le mode tresse.

- Héros = moi je, immersion
- Chaos = le troll, aime jouer les méchants
- Cosmos = le cinéphile, le littéraire, l'arbitre

En mode tresse, c'est Cosmos qui gère le destin. Et dans les oppositions, il intervient pour ajouter des dés aux protagonistes ou à l'obstacle suivant les dés du destin qu'il a en main. Il doit bien sûr justifier les dés posés par des éléments du contexte.

C'est également Cosmos qui interprète le résultat de l'opposition sauf si Chaos prend la main au nom de l'histoire.

Cela ne gêne normalement pas la fiction car juste après l'interprétation, Chaos peut tout à fait retourner dans la fiction et raconter un élément propre à l'intrigue.

_Règle optionnelle: quand Chaos se saisit de l'interprétation d'un résultat au nom de l'histoire, le destin gagne un point et donc Cosmos gagne un dé protagoniste (bleu). A appliquer si Chaos a tendance à empiéter sur les interprétations de Cosmos._

== Mode legacy

Dans ce mode, on a:

* La **Destinée**: le joueur en charge du monde, des menaces et de l'intrigue (il cumule Cosmos et Chaos du mode tresse en fait).
* Les **Héros**: les joueurs en charge des protagonistes

Lors du cadrage, la **Destinée** répondra aux questions du cadrage mais pourra proposer des choix aux **Héros**.

Note: généralement la Destinée a déjà un univers prêt à jouer dans ce type de mode.

== Mode solo

Un seul joueur joue le rôle de Chaos, Cosmos et des Héros. Il s'appuie dans ce cas sur les Oracles pour rajouter de la surprise et sur le destin pour connaitre l'orientation des événements: positifs ou négatifs ou neutres.

Une autre façon de jouer est de faire en solo des cadrages et des préparations pour préparer une prochaine partie en mode legacy.