= Les ressources
:doctype: book

Le jeu s'appuie sur les ressources suivantes:

* Des questions
* Des lexiques

Ces ressources sont très simples à utiliser, à modifier ou à créer. N'hésitez pas à enrichir votre jeu en créant les vôtres.

== Les questions

Les questions permettent tout simplement de créer un élément du jeu en répondant à des questions.

Les réponses sont globalement libres mais doivent être en accord avec les autres éléments du jeu et avec les autres joueurs.

En général les questions sont formulées explicitement mais il est possible aussi d'avoir des ressources **questions** sous forme de "formulaire" avec des champs à remplir.

== Les lexiques

Les lexiques sont tout simplement des listes de noms, expressions qui pourront servir la narration mais également de facteurs clés dans  une opposition.

C'est aussi simple que cela.

Un lexique peut également constitué d'éléments sonore ou d'images. Ce n'est pas limité qu'aux mots.

Notez qu'une fois les réponses connues d'une liste de question, on obtient un lexique. Il y a donc un lien entre questions et lexiques.

Notez également que certains lexiques peuvent servir d'Oracle. Il suffit d'appliquer la méthode de détermination spécifiée dans le lexique (dé, cartes, autres...) ou d'utiliser une application de génération de nombre pour connaitre le résultat.

En mode tresse, les lexiques sont surtout utilisés par Cosmos et un peu par Chaos.
